openapi: 3.0.0
info:
  title: Account
  description: 사용자 인증 및 가입, 로그인, 탈퇴 등
  version: "1.0.0"
tags:
  - name: inflow
    description: 사용자 유입
  - name: secured
    description: 인증된
  - name: account
    description: 내 계정 찾기
  - name: users
    description: 사용자 관리
paths:
  /signin:
    post:
      summary: 이메일, 모바일 로그인
      tags:
        - inflow
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: OK
  /signup:
    post:
      summary: 이메일, 모바일 가입
      tags:
        - inflow
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: OK
  /verify:
    get:
      summary: 이메일, 모바일 인증
      tags:
        - inflow
      parameters:
        - $ref: '#/components/parameters/hashCode'
      responses:
        '200':
          description: OK
  /search/account:
    post:
      summary: 계정 찾기
      tags:
        - account
      requestBody:
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/FindForm'
      responses:
        '200':
          description: OK
  /invite:
    get:
      summary: 사용자 초대
      tags:
        - secured
        - inflow
      parameters:
        - $ref: '#/components/parameters/hashCode'
        - $ref: '#/components/parameters/email'
        - $ref: '#/components/parameters/mobile'
      responses:
        '200':
          description: OK
  /reset/account:
    post:
      summary: 비밀번호 초기화
      tags:
        - account
      requestBody:
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/FindForm'
      responses:
        '200':
          description: OK
  /me:
    get:
      summary: 내 정보 조회
      tags:
        - secured
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      summary: 내 정보 수정
      tags:
        - secured
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: OK
    delete:
      summary: 탈퇴
      tags:
        - secured
      responses:
        '200':
          description: OK
  /users:
    post:
      tags:
        - "users"
      responses:
        '200':
          description: OK
    put:
      tags:
        - "users"
      responses:
        '200':
          description: OK
    get:
      tags:
        - "users"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserList'
    delete:
      tags:
        - "users"
      responses:
        '200':
          description: OK
  /users/{userNo}:
    get:
      tags:
        - "users"
      parameters:
        - $ref: '#/components/parameters/userNo'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      
components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
          example: "test@example.com"
        mobile:
          type: string
          example: "01012345678"
        password:
          type: string
          format: "password"
          example: "********"
    FindForm:
      type: object
      properties:
        email:
          type: string
          example: "test@example.com"
        mobile:
          type: string
          example: "01012345678"
    UserList:
      type: array
      items:
        $ref: '#/components/schemas/User'
  parameters:
    hashCode:
      name: code
      description: 8 characters hash
      in: query
      schema:
        type: string
      example: 3106cdf2
    email:
      name: email
      in: query
      schema:
        type: string
      example: "test@example.com"
    mobile:
      name: mobile
      in: query
      schema:
        type: string
      example: "01012345678"
    userNo:
      required: true
      name: userNo
      in: path
      schema:
        type: integer
        example: 11