openapi: 3.0.0
info:
  title: Event
  version: "1.0.0"
tags:
  - name: Event
    description: 이벤트
  - name: KPI
    description: 데이터 지표 (Event Performance Indicator)
  - name: Rule
    description: 데이터 규칙 (Event Schedule)
paths:
  /events:
    post:
      summary: KPI 및 Rule 등록
      tags:
        - KPI
        - Rule
      responses:
        '200':
          description: OK
    get:
      summary: Event 및 Record 리스트
      tags:
        - Event
      responses:
        '200':
          description: OK
  /kpis:
    get:
      summary: KPI 및 Rul
      tags:
        - KPI
      responses:
        '200':
          description: OK
  /rules:
    get:
      summary: KPI 및 Rul
      tags:
        - Rule
      responses:
        '200':
          description: OK