openapi: 3.0.0
info:
  title: Event
  version: "1.0.0"
tags:
  - name: Event
    description: 사용자 이벤트
paths:
  /events:
    post:
      summary: Event 등록
      tags:
        - Event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: OK
  /events/{eventNo}:
    get:
      summary: Event 조회
      tags:
        - Event
      parameters:
        - $ref: '#/components/parameters/eventNo'
      responses:
        '200':
          description: OK
  /events/search:
    get:
      summary: Event 검색
      tags:
        - Event
      responses:
        '200':
          description: OK

components:
  schemas:
    Event:
      type: object
      properties:
        type:
          type: string
          example: "imp / clk"
        value:
          type: string
  parameters:
    eventNo:
      required: true
      name: userNo
      in: path
      schema:
        type: integer
        example: 11
