openapi: 3.0.0
info:
  title: Log
  version: "1.0.0"
tags:
  - name: Log
    description: 사용자 이벤트
paths:
  /logs:
    post:
      summary: Log 검색
      tags:
        - Log
      responses:
        '200':
          description: OK
    get:
      summary: Log 조회
      tags:
        - Log
      parameters:
        - $ref: '#/components/parameters/userNo'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Log'
  /logs/{eventNo}:
    get:
      summary: Log 조회
      tags:
        - Log
      parameters:
        - $ref: '#/components/parameters/eventNo'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Log'
  /logs/search:
    post:
      summary: Log 검색
      tags:
        - Log
      responses:
        '200':
          description: OK

components:
  schemas:
    Log:
      type: object
      properties:
        type:
          type: string
          example: "imp / clk"
        value:
          type: string
  parameters:
    eventNo:
      required: true
      name: eventNo
      in: path
      schema:
        type: integer
        example: 333
    userNo:
      required: true
      name: userNo
      in: query
      schema:
        type: integer
        example: 11
